# apps/app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts      # Helm chart source
    chart: grafana
    targetRevision: 6.61.0                               # Pick your desired version
    helm:
      valueFiles:
        - apps/grafana/values.yaml                       # Path in your GitHub repo
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts  # ✅ Direct chart source
    chart: kube-prometheus-stack
    targetRevision: 58.2.0     # Or latest version you want
    helm:
      valueFiles:
        - apps/prometheus/values.yaml  # ✅ Relative to your Git repo
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

