# Grafana Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/shaits/azure-k8s-monitoring-kub        # Your GitHub repo
    targetRevision: main
    path: apps/grafana                                                 # Only contains values.yaml
    helm:
      chart: grafana
      repo: https://grafana.github.io/helm-charts                      # Official chart repo
      targetRevision: 6.61.0                                           # Or latest stable
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
# Prometheus Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/shaits/azure-k8s-monitoring-kub        # Your GitHub repo
    targetRevision: main
    path: apps/prometheus                                              # Only contains values.yaml
    helm:
      chart: kube-prometheus-stack
      repo: https://prometheus-community.github.io/helm-charts         # Official chart repo
      targetRevision: 58.2.0                                           # Or latest stable
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
